[book]
authors = ["MPI-BC tSCN / TUM Chronobiology & Health"]
language = "en"
multilingual = false
src = "src"
title = "MPI-BC tSCN / TUM Chronobiology & Health Lab Handbook"

[output.html]
additional-css = ["custom.css"]
